### ISSUE TITLE
Add Spine Runtime in Third Party Extensions

### ISSUE THREAD

**Issue by raeleus** [tommyettinger/gdx-liftoff#10]
One more, sorry! Please add the Spine Runtime to the Third Party Extensions. It's a super popular lib, though it is paid software. Runtime info can be found here: https://github.com/EsotericSoftware/spine-runtimes/tree/3.8/spine-libgdx#gradle

Thanks a billion!

**Comment by tommyettinger** [comment]
Done! I think. I'm not 100% sure on the GWT deps, since they aren't documented.

**Comment by tommyettinger** [comment]
I think this is fixed in https://github.com/tommyettinger/gdx-liftoff/releases/tag/v1.9.10.6 .
