### ISSUE TITLE
Add support for the experimental TeaVM backend from gdx-web-tools by xpenatan

### ISSUE THREAD

**Issue by czyzby** [tommyettinger/gdx-liftoff#102]
[xpenatan/gdx-html5-tools](https://github.com/xpenatan/gdx-html5-tools/) is an alternative web backend that works on bytecode rather than Java sources, which makes it compatible with other JVM languages such as Kotlin. It also supports some official plugins such as Box2D, as well as extensions that are normally not available on GWT like Bullet or Freetype. While it's still experimental and offers only snapshot releases, I think it's a worthwhile addition due to its Kotlin support alone.

**Comment by tommyettinger** [comment]
This is really cool! I merged the initial PR, I'm planning to merge any followups for this.
