### ISSUE TITLE
Android immersive mode

### ISSUE THREAD

**Issue by JojoIce** [tommyettinger/gdx-liftoff#108]
Hi,

Not sure if this has been thought of and discarded, but Gdx is generally used for games and one typically does not want the "navigation bar" on the screen for pads or phones that do not have physical buttons. So I personally always add one line in the AndroidLauncher (middle line added):
```		
		AndroidApplicationConfiguration configuration = new AndroidApplicationConfiguration();  
		configuration.useImmersiveMode = true;  //Adding this!
		initialize(new GameStarter(), configuration); 
```
Very minor thing, but this tool is so great that it only is minor things left to possibly tweak.

**Comment by Frosty-J** [comment]
It'll be true by default in libGDX 1.11.1, but I don't see why not set it to true today in Liftoff.

**Comment by tommyettinger** [comment]
Good idea, and if it's going to be true by default, it should be safe now, I would think. I'm adding this now.
