### ISSUE TITLE
android buildToolsVersion missing

### ISSUE THREAD

**Issue by kloylar** [tommyettinger/gdx-liftoff#11]
when building android platform, the line 
buildToolsVersion '2x.x.x' 
is missing in file build.gradle generating a build error 
AAPT: error: attribute android:appCategory not found.

**Comment by tommyettinger** [comment]
I just built a debug APK, installed it on my phone (Samsung Galaxy S8), and it ran fine. I'm using build tools 28.0.3, and I don't think the current Gradle config needs the build tools specified. It's possible that there's a breaking change in later build tool versions. If I remember this right, liftoff used to put a build tools version in `android/build.gradle`, but an IDEA update gave a warning when that version was specified, saying it was no longer needed. I could easily be wrong about the file or other specifics.

What version of build tools are you using (in general, more Android info would be useful), and what Gradle command did you run that gave that error? I'm assuming you already updated to the current gdx-liftoff before posting an issue.

I don't know if I have enough disk space to install Android Studio in addition to IDEA; I am extremely low on available space, so it would be a challenge for me to test other build tool versions.

**Comment by tommyettinger** [comment]
I just built an APK version with and without build tools specified, so I'm not sure what omitting it does...

**Comment by tommyettinger** [comment]
OK, buildToolsVersion is present now in the latest code (not in a release yet); I don't know if that's sufficient for a fix, but I think I can close this.
