### ISSUE TITLE
Warning duplicate content roots and error with Android

### ISSUE THREAD

**Issue by Quillraven** [tommyettinger/gdx-liftoff#117]
Hi,

I created a fresh new project for desktop, teavm and android and get following warning/errors in IDEA:
![image](https://user-images.githubusercontent.com/93260/218133047-49d04574-abbf-4cae-974c-b467b0d0debd.png)

The warning only comes when adding more than one "backend" for the game. I guess it can be ignored because teavm+desktop are both working. But maybe there is a solution to get rid off the warning?

For the error I guess I am doing something wrong. Maybe I need a different SDK for the project or some other setting?
I used this SDK:
![image](https://user-images.githubusercontent.com/93260/218133558-f05f1346-76e1-4dad-a3fc-681c8cd4f365.png)

and also downloaded the API level 32 stuff:
![image](https://user-images.githubusercontent.com/93260/218133712-f94ffb57-dffd-4735-8764-3af0515c847a.png)

But when I go the Androindlauncher it cannot even compile properly:
![image](https://user-images.githubusercontent.com/93260/218133864-ccb8fbef-93e7-451d-baaa-19102fffa936.png)

Any help with the error is appreciated, thank you!

**Comment by Frosty-J** [comment]
The warning is normal and also happens with gdx-setup. It may be due to the assets directory being in root / shared between modules.

I don't know why it's erroring, but I must admit I haven't tried the latest gdx-liftoff release.

**Comment by Quillraven** [comment]
When you have time, can you please try it and let me know if it works for you?

**Comment by Quillraven** [comment]
Another small thing that I noticed: the .gitignore does not exclude the build folder of lwgjl3 and teavm. Imo this should be added:

```
/lwjgl3/build/
/teavm/build/
```

**Comment by Frosty-J** [comment]
Line 8 of `.gitignore` already excludes `/lwjgl3/build/`. But there's no `teavm` in there. Using wildcards like `/*/build/` etc. would be more future-proof.

Works for me - I just had to change `compileSdk` and `targetSdkVersion` from `34` to `33` for it to build. I also tried with the Kotlin template, since your error looks Kotlin-y, but wasn't able to reproduce the same `log()` deal.

**Comment by Quillraven** [comment]
Thank you @Frosty-J! I now simply ticked all SDK platforms down to 29 and after a restart the of IDEA the errors are now gone.

![image](https://user-images.githubusercontent.com/93260/218245275-f606b809-6f08-4a3c-8c25-751c4620fffd.png)

Thanks again for your help :)

**Comment by Frosty-J** [comment]
I will never truly understand Android. Cursed solution, but disk space is cheap so the important thing is it works.

**Comment by tommyettinger** [comment]
TeaVM will be included in .gitignore in the next release. That will probably come out when Gradle 8.0 does.
