### ISSUE TITLE
KTX AI module

### ISSUE THREAD

**Issue by czyzby** [tommyettinger/gdx-liftoff#125]
* Add the new `ktx-ai` module with a `gdxAI` dependency to the list of the third-party extensions.
* Update the default KTX version to 1.11.0-rc6.

**Comment by tommyettinger** [comment]
Oh, I added this myself without seeing this... I'll check that they're equivalent...

**Comment by czyzby** [comment]
I haven't gotten around to add a PR yet, thanks! :)
