### ISSUE TITLE
Trojan detected (1.11.0.9 only)

### ISSUE THREAD

**Issue by Developpix** [tommyettinger/gdx-liftoff#126]
Hello,

A trojan is reported in your last jar 1.11.0.9

https://www.virustotal.com/gui/file/65aceaf78f60ba4c11149c422b28961a58c4d56be5ad2dd1da7e9ab468ef45e7

**Comment by Frosty-J** [comment]
False positive, as is typical when you scan something with 50 engines. Never heard of "Rising".

**Comment by tommyettinger** [comment]
Indeed. https://www.virustotal.com/gui/file/65aceaf78f60ba4c11149c422b28961a58c4d56be5ad2dd1da7e9ab468ef45e7 shows nothing detected. I bet if you click re-analyze enough times you can get it to say anything.
