### ISSUE TITLE
Update libKtx version

### ISSUE THREAD

**Issue by heatherhaks** [tommyettinger/gdx-liftoff#13]
the default libgdx version is 1.9.10 but the default libktx versions are still for 1.9.8. They should be updated to the latest 1.9.10 version which as of the time of this issue's creation is 1.9.10-b6

**Comment by tommyettinger** [comment]
Got it, on it.

**Comment by tommyettinger** [comment]
I added the 7 missing KTX libraries and updated to 1.9.10-b6, I'm pretty sure it all works but some of the libraries may have different Gradle dependencies than what I have currently. They seem pretty consistent within KTX though, and I think I got the deps right for all 20 or so.
