### ISSUE TITLE
Issue in project opening

### ISSUE THREAD

**Issue by akashKarmakar02** [tommyettinger/gdx-liftoff#145]
Class org.jetbrains.kotlin.idea.gradleTooling.KotlinGradleModel must not be requested from main classloader of org.jetbrains.kotlin plugin [Plugin: org.jetbrains.android]

when i open a new project desktop only with java version 21 and gradle version 8.5

**Comment by akashKarmakar02** [comment]
It is fixed it is happend due to old kotlin plugin

**Comment by tommyettinger** [comment]
Interesting, I'll try to update it in Liftoff if possible. I had an issue when launching Gradle with Java 21 and trying to build an Android APK from IDEA, but it wasn't the same bug you reported. The bug I hit was resolved by changing the setting in IDEA to run Gradle with Java 17. In case anyone finds this by searching, the error was:
```
> Task :android:compileReleaseJavaWithJavac FAILED

Execution failed for task ':android:compileReleaseJavaWithJavac'.
> Could not resolve all files for configuration ':android:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: C:\Users\tommy\AppData\Local\Android\Sdk\platforms\android-34\core-for-system-modules.jar.
         > Error while executing process C:\d\jvm\jdk21-hotspot\bin\jlink.exe with arguments {--module-path C:\Users\tommy\.gradle\caches\transforms-3\553ad13d8645437e7a391ae3ab1b8dbb\transformed\output\temp\jmod --add-modules java.base --output C:\Users\tommy\.gradle\caches\transforms-3\553ad13d8645437e7a391ae3ab1b8dbb\transformed\output\jdkImage --disable-plugin system-modules}
```

I've never seen this type of bug before, and I didn't know Android even used jlink...

**Comment by akashKarmakar02** [comment]
Try `./gradlew clean` 
After that try building again It sometimes fixed the problem
