### ISSUE TITLE
Could not find or load main class

### ISSUE THREAD

**Issue by Quillraven** [tommyettinger/gdx-liftoff#18]
A user mentioned in one of my tutorial videos that he was not able to run gdxliftoff because the main class could not be found.
Here is the comment:

```
Nice tutorial. However, I was getting the following error. 
Error: Could not find or load main class gdx-liftoff-1.9.10.11.jar. 
I fixed it by running: java  -jar gdx-liftoff-1.9.10.11.jar  
I'm not sure why this was the case, but it worked. Is there a better way to fix this?
```

Do you know why that happens or how to fix it? I personally did not face this issue so far.

**Comment by tommyettinger** [comment]
Yeah, it's not a bug in gdx-liftoff. That happens when you  try to run a JAR with `java something.jar`, and the user's fix to use `java -jar something.jar` is correct. I verified what gives that bug here: ![NoBug](https://i.imgur.com/JNPWTqs.png)

**Comment by Quillraven** [comment]
I only DoubleClick the icon e.g.. Can you somehow modify the click behavior that it does java ... instead of java -jar ...?

**Comment by tommyettinger** [comment]
I really have no idea how that would happen, but I'm sure someone's system, somewhere, has that configuration.
