### ISSUE TITLE
Fullscreen messes up the resolution

### ISSUE THREAD

**Issue by payne911** [tommyettinger/gdx-liftoff#20]
![image](https://user-images.githubusercontent.com/38117856/91793852-5c7ead80-ebe7-11ea-8996-e308c91bdbff.png)

**Comment by tommyettinger** [comment]
Yep, heh. I'm not sure how to handle this... It uses StretchViewport currently, so if you're manually resizing the window, you can fit it so it looks good on your monitor. Supporting a wider or taller font is a useful accessibility feature; on the Discord you can ask cococore about his custom font that acts like a very tall stretch on the window. If we make the window only able to scale at a 1:1 aspect ratio, I worry about it becoming hard to read on unusually-sized screens, or for users who need visual adaptation. The easiest fix for this if you're using Windows is to drag the window to the side, making it take up half the screen.
