### ISSUE TITLE
Understanding Headless, Server, and Shared modules

### ISSUE THREAD

**Issue by GiantFrog** [tommyettinger/gdx-liftoff#35]
Hi, awesome project, sorry if this isn't quite the right place for this!

Other than the quick mouseover, I can't find any documentation on what these modules actually do or when I would want to use them. Since Headless says it can be used for testing or a server, do I use that for a terminal-only server and the Sever module if I want to make a server with a GUI? And what exactly does Shared do that Core does not?

I cannot tell what I might need and I just assume it's pretty hard to change things after generation, at least if it's anything like the official setup jar.

**Comment by GiantFrog** [comment]
And, um, just one other thing. I can't seem to select a Java version higher than 14, even if I have 15 installed. On Linux and Windows, adoptopenjdk hotspot. But things seem to just work anyway, at least so far.

After messing around on my own, I decided to go with a Headless for my server, and no Shared or Server modules.

**Comment by tommyettinger** [comment]
Hello! The whole headless/server/shared distinction is odd, and I inherited it from the earlier setup app by czyzby, where I don't think it was documented any differently. From all I can figure out:

  - Headless depends on Core, and can be run as a terminal app, including on a machine without any display (such as server hardware). I've used the headless backend for tests and tools.
  - Server doesn't depend on anything except Shared, if it's present, which means it doesn't have access to any libGDX classes. I'm not really sure what the benefit is for having Server located in the same project as the other modules, unless you have a Shared module that Server and Core both use.
  - Shared I believe gets used by both Core and Server, if present, and is meant for data that gets transferred from client to server and/or back again. It doesn't depend on libGDX either.

There's been some discussion of this and no one seems to have a single way forward that works for all the client-server cases. I can recommend looking through https://github.com/payne911/marvelous-bob as a sample of how to structure a networked game with libGDX; I believe the shared module is called "common" there. You have probably got a good approach anyway by going with Headless for the server and handling the data transferred with some interchange format, like JSON. If you want to serialize some game object in the client, send it over the network and deserialize it on the server, you can also make use of a shared/common module of the game classes that need transferring (which could depend on libGDX, to use its Json class and data structures), and depend on the shared module in your client and in your headless module. In that case, you could use Kryo and KryoNet to handle ser/deser and network transmission of the serialized objects.

You're right that it's a hassle to change module structure after generation; there isn't much I can do about that. It isn't too hard to re-generate a project with different options and copy in the source into core (and maybe your headless module, in your case) again. That gets annoying if you've customized lots of Gradle files, though.

RE Java 15, I'm slightly surprised but I think I can fix that. Gradle is up to 6.7.1 now and I can update that too.

**Comment by payne911** [comment]
> Other than the quick mouseover, I can't find any documentation on what these modules actually do or when I would want to use them.

That's one of the reasons why I created that other project: https://github.com/payne911/gdx-setup-generator

It provided a preview feature so that you can know right away what the generated project would look like.

... But no one ever adopted it, so I just abandoned it.

**Comment by GiantFrog** [comment]
Ah, thank you so much, you two! I didn't realize Server was completely independent, even from Core. That explains why Shared would be useful. I think using libGDX for my server would be best for my project, so I'll stick with Headless! It seems perfect for my intentions.

Not that it's important, but I'm shooting for Kryo + Netty instead of KryoNet. I'm new to both, my old game just sent strings back and forth on a TCP socket... But I'll figure it out, what could go wrong?

@tommyettinger I'll regenerate with Java 15 now, thanks for making that update for me! ^_^

**Comment by payne911** [comment]
> I think using libGDX for my server would be best for my project, so I'll stick with Headless! It seems perfect for my intentions.

You mentioned wanted a GUI for your server: the `headless` way will not fulfill your requirement.

**Comment by GiantFrog** [comment]
> You mentioned wanting a GUI for your server

Oh, actually, I don't want one. It was more of a "theoretically, do I use this module if I wanted a GUI server and that module if I wanted a command line one" sort of question. Not that it really matters! But all is right in the world.
