### ISSUE TITLE
The new file desn't run under Java 11 for some reason

### ISSUE THREAD

**Issue by Zishan-Rahman** [tommyettinger/gdx-liftoff#36]
Hi all.

I tried to run the latest JAR file under Java 11 but for some reason I'm getting these exceptions:

![cmd_yh7yrZ2L6f](https://user-images.githubusercontent.com/45298929/101897996-4fd50280-3ba3-11eb-9df7-f502eceefc2a.png)

Here's the full details on my Java installation (for reference):

![cmd_ddjapRte5A](https://user-images.githubusercontent.com/45298929/101898044-65e2c300-3ba3-11eb-9891-51ef4facbf87.png)

How to reproduce the problem: Download AdoptOpenJDK version 11, install it, set it to JAVA_HOME and try to run the new Liftoff JAR through it.

So what's going on and what do I do about it?

Zishan Rahman.

**Comment by tommyettinger** [comment]
You're correct, it was accidentally built with Java 15 when I should have used Java 8. I'm updating the release right now, with a JAR that should run with any Java 8 or higher.

**Comment by Zishan-Rahman** [comment]
> You're correct, it was accidentally built with Java 15 when I should have used Java 8. I'm updating the release right now, with a JAR that should run with any Java 8 or higher.

OK, thanks!
