### ISSUE TITLE
Project generation error

### ISSUE THREAD

**Issue by PotaytoPrograms** [tommyettinger/gdx-liftoff#37]
When ever I try to make a project, with either LWJGL3 or Desktop(Leagacy), I allways get the same error:
Preparing the project...
com.badlogic.gdx.utils.GdxRuntimeException: Error copying source file: icons\libgdx16.png (Internal)
To destination:...(lwjgl3/Desktop)\src\main\resources\libgdx16.png (Absolute)
  at com.badlogic.gdx.files.FileHandle.copyFile(FileHandle.java:718)
  at com.badlogic.gdx.files.FileHandle.copyTo(FileHandle.java:603)
  at com.github.czyzby.setup.data.files.CopiedFile.save(projectFile.kt:106)
  at com.github.czyzby.setup.data.project.Project.saveFiles(project.kt:121)
  at com.github.czyzby.setup.data.project.Project.generate(project.kt:89)
  at com.github.czyzby.setup.views.dialogs.GenerationPrompt$doBeforeShow$1.run(generationPrompt.kt:45)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
Unable to generate project due to an exception. Try again.

OS: windows 10
Java: 8
This is on the latest gdx-liftoff version: 1.9.12.1

**Comment by PotaytoPrograms** [comment]
Ok so this actually happens on every version (I haven't tried them all)

**Comment by PotaytoPrograms** [comment]
Well Ive updated to Java 15, still doesnt work, BTW I'm using amazon corretto cause oracle sucks

**Comment by tommyettinger** [comment]
Looking into it now... I haven't seen this before. I just made sure that file is present in the latest JAR, and it is.

 ![Screenshot of 7-Zip](https://i.imgur.com/tF6as7y.png)

Are you sure you have write access to the project folder you're making, and that Windows 10 or some overzealous antivirus software isn't blocking file writes by liftoff?

**Comment by PotaytoPrograms** [comment]
That must be the case, im on my laptop (Linux) right now and it works, I'll have to wait till I get home to fix, Thanks for your time.

**Comment by tommyettinger** [comment]
Huh, well thanks for trying again on Linux; I wonder what could be the problem on Windows... A corrupted JAR download is possible, but not especially likely. If downloading the Liftoff JAR had some error on the network or drive, then that icon file could actually be missing from your specific JAR file; re-downloading could help. Windows could be blocking just-downloaded JARs, or even could be restricting the actions java.exe (or javaw.exe, more likely) can take, if the JDK installation isn't trusted for some reason. I don't think this is a problem with Liftoff, but it is still possible. Just like downloading, my upload could have had some failure when I uploaded the current Liftoff release. I'll download my own release and make sure it's correct.

**Comment by tommyettinger** [comment]
Yeah, the release seems correct; I validated the checksum against my local version, and also downloaded 1.9.12.1 again and made a new project just fine. This definitely seems like it could be a problem with your particular Windows 10 installation, if it isn't a problem with the downloaded JAR. If it is a Windows or antivirus issue, I'm sure the next person to encounter the issue would be very grateful to hear how you solve it! Please, keep trying stuff, but I don't know how much help I can be since I have only been using Windows 10 regularly for a few months.

**Comment by PotaytoPrograms** [comment]
Yes it was my antivirus, I have only been using windows regularly for a few weeks myself :P .
