### ISSUE TITLE
iOS requires fullscreen

### ISSUE THREAD

**Issue by JojoIce** [tommyettinger/gdx-liftoff#40]
Tested to send an iOS build to Apple again after they finally fixed my account... 

There seems to be one small problem still with the Info.plist.xml

Just add:
`
		<key>UIRequiresFullScreen</key>
		<true/>
`
Somewhere in the dict. See [Invalid Bundle. iPad Multitasking support requires launch story board in bundle](https://developer.apple.com/forums/thread/20405)

**Comment by tommyettinger** [comment]
Thanks a bunch; this is now included in Info.plist.xml .
