### ISSUE TITLE
ProGuard file generated for android has the wrong name

### ISSUE THREAD

**Issue by fgnm** [tommyettinger/gdx-liftoff#44]
Hi, I've noticed that the name of ProGuard file is not the same of the one listed in default gradle generated into android module.

In the gradle we have `proguard-rules.pro`
https://github.com/tommyettinger/gdx-liftoff/blob/4853024550a62fa677a54664749d2450f86cd971/src/main/kotlin/com/github/czyzby/setup/data/platforms/android.kt#L147

But the file generated is `proguard-project.txt`: https://github.com/tommyettinger/gdx-liftoff/blob/master/src/main/resources/generator/android/proguard-project.txt

Generated file should be renamed into `proguard-rules.pro` :)

**Comment by tommyettinger** [comment]
Great, thanks, I'll rename the file now.
