### ISSUE TITLE
Android box2d build failing 1.10.0

### ISSUE THREAD

**Issue by antiqu** [tommyettinger/gdx-liftoff#45]
I updated my project from libgdx version 1.9.14 to 1.10.0,  and noticed the build was failing on android.
I run the program via cmd (gradlew android:installDebug)

![ss1](https://user-images.githubusercontent.com/6242017/115925044-3749f280-a489-11eb-8556-3234c1ff2a6d.jpg)

It seems after removing the lines from android/build.gradle fixed the problem.

natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-armeabi"
natives "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-armeabi"

**Comment by tommyettinger** [comment]
Ah, geez, good catch. The armeabi binaries were removed and I hadn't changed liftoff accordingly. I think that architecture is rare enough that I can remove the armeabi dependencies for older versions as well as the current 1.10.0. Thanks!
