### ISSUE TITLE
Giving an error to a correct directory for Android SDK

### ISSUE THREAD

**Issue by ronjunevaldoz** [tommyettinger/gdx-liftoff#46]
Giving an error to a correct directory for Android SDK
![image](https://user-images.githubusercontent.com/4947998/116649348-a5bf1100-a9b1-11eb-8d9a-551bd93ef099.png)

**Comment by tommyettinger** [comment]
What are the contents of `E:/Android/Sdk` ? For me, when I list the contents of a working Sdk directory, I get:
```
build-tools/
emulator/
extras/
licenses/
patcher/
platform-tools/
platforms/
skins/
sources/
system-images/
tools/
```
It would also help to know what version of Android SDK you have installed; maybe some newer versions don't validate correctly.

**Comment by ronjunevaldoz** [comment]
It was working correctly when using libgdx setup, using same e:/Android/Sdk directory

**Comment by bestiardo** [comment]
> It was working correctly when using libgdx setup, using same e:/Android/Sdk directory. Below is the screenshot for your reference.
> 
> ![image](https://user-images.githubusercontent.com/4947998/116713024-0298e680-aa07-11eb-92e4-541788113f05.png)

create a tools directory. it work for me

**Comment by tommyettinger** [comment]
This should be fixed in https://github.com/tommyettinger/gdx-liftoff/releases/tag/v1.10.0.3 . It looks like `tools` was renamed to `cmdline-tools` in some recent version of the Android SDK, so now liftoff will check if either is present (as well as needing `platforms`) to validate an SDK directory.
