### ISSUE TITLE
Update default version of Typing Label to 1.2.0

### ISSUE THREAD

**Issue by raeleus** [tommyettinger/gdx-liftoff#6]
Hello. Do you mind updating the default version of Typing Label to the recent release (1.2.0)? Muchas Gracias.

**Comment by tommyettinger** [comment]
It's already been updated, there just hasn't been a release yet. I think I may postpone the Kotlin source feature in #5 because I'm not at all sure how I would do it, and release a version sooner.

**Comment by tommyettinger** [comment]
This is fixed in https://github.com/tommyettinger/gdx-liftoff/releases/tag/v1.9.10.6 .
