### ISSUE TITLE
Add TenPatch to third party extensions

### ISSUE THREAD

**Issue by raeleus** [tommyettinger/gdx-liftoff#7]
Hello. I would like to humbly request that you add TenPatch to the third party extensions of your app. I don't really know how to get figures on how many people use my lib, but it's a number greater than 0. It's a really useful extension for those that use it, however! If you must deny my request, it could be done without any negative feelings or ill wishes from my side.

See more about my project: https://github.com/raeleus/TenPatch

Thank you for considering my request!

**Comment by tommyettinger** [comment]
I'd be happy to add it! I'm adding a few other third-party libraries while I'm on the topic.

**Comment by raeleus** [comment]
Thank you so much for your quick response!

**Comment by tommyettinger** [comment]
This is fixed in https://github.com/tommyettinger/gdx-liftoff/releases/tag/v1.9.10.6 .
