### ISSUE TITLE
`gdxdialogs` dependencies seem to have an incorrect groupId

### ISSUE THREAD

**Issue by GuDzpoz** [tommyettinger/gdx-liftoff#74]
In [thirdPartyExtensions.kt#L173](https://github.com/tommyettinger/gdx-liftoff/blob/master/src/main/kotlin/gdx/liftoff/data/libraries/unofficial/thirdPartyExtensions.kt#L173):
```
    override fun initiateDependencies(project: Project) {
        addDependency(project, Core.ID, "de.tomgrill.gdxdialogs:gdx-dialogs-core")

        addDependency(project, Android.ID, "de.tomgrill.gdxdialogs:gdx-dialogs-android")

        addDesktopDependency(project, "de.tomgrill.gdxdialogs:gdx-dialogs-desktop")

        addDependency(project, iOS.ID, "de.tomgrill.gdxdialogs:gdx-dialogs-ios")

        addDependency(project, GWT.ID, "de.tomgrill.gdxfacebook:gdx-dialogs-core:sources")
        addDependency(project, GWT.ID, "de.tomgrill.gdxfacebook:gdx-dialogs-html")
        addDependency(project, GWT.ID, "de.tomgrill.gdxfacebook:gdx-dialogs-html:sources")
        addGwtInherit(project, "de.tomgrill.gdxfacebook.html.gdx_dialogs_html")
    }
```

`de.tomgrill.gdxfacebook:gdx-dialogs-core:sources` `de.tomgrill.gdxfacebook:gdx-dialogs-html` `de.tomgrill.gdxfacebook:gdx-dialogs-html:sources` should probably be `de.tomgrill.gdxdialogs:...` as is in the [Maven Repository](https://mvnrepository.com/artifact/de.tomgrill.gdxdialogs/gdx-dialogs-core/1.3.0). (Did they changed the groupId somehow?)

**Comment by tommyettinger** [comment]
Thanks for reporting this; it should be fixed now. It isn't in 1.10.0.9, but should be in this attached snapshot build.
[gdx-liftoff-1.10.0.10-SNAPSHOT.jar.zip](https://github.com/tommyettinger/gdx-liftoff/files/7729405/gdx-liftoff-1.10.0.10-SNAPSHOT.jar.zip)
