### ISSUE TITLE
Unrecognized VM option 'MaxPermSize=1G' with OpenJDK 17

### ISSUE THREAD

**Issue by JupiterRider** [tommyettinger/gdx-liftoff#75]
Remove the argument `-XX:MaxPermSize=1G` in the gradle.properties file of a generated project.

See [https://docs.oracle.com/en/java/javase/17/docs/specs/man/java.html#removed-java-options](https://docs.oracle.com/en/java/javase/17/docs/specs/man/java.html#removed-java-options):

Removed Java Options

These java options have been removed in JDK 17 and using them results in an error of:

-XX:MaxPermSize=size
    Sets the maximum permanent generation space size (in bytes). This option was deprecated in JDK 8 and superseded by the -XX:MaxMetaspaceSize option.

**Comment by tommyettinger** [comment]
Uh, OK. I wasn't expecting that. I'd like to replace with -XX:MaxMetaspaceSize , as long as it's still supported by both 17 and 8. I'll look into this, and I might just remove the max size for this entirely.
