### ISSUE TITLE
Current MobiVM Gradle plugin is not compatible with the Gradle 7.3.3

### ISSUE THREAD

**Issue by metaphore** [tommyettinger/gdx-liftoff#78]
Hi, I didn't really investigate on the cause, but I've just used the latest `1.10.0.10` release  to generate a new project and it seems that MobiVM iOS backed is not fully compatible with the latest Gradle (with the major release 7 in general?).

Here's what I get from trying to assemble an IPA from the freshly generated project.

```
./gradlew createIPA
> Task :ios:createIPA FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':ios:createIPA' (type 'ArchiveTask').
  - In plugin 'robovm' type 'org.robovm.gradle.tasks.ArchiveTask' property 'roboVMLogger' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#missing_annotation for more details about this problem.
```

**Comment by tommyettinger** [comment]
![Current state of mind](https://i.imgur.com/GfMsxzH.gif)

This has been reported before; I remember seeing notifications about it on RoboVM's GitHub repos. I'm marginally surprised that it hasn't been fixed, though I probably shouldn't be. There's an open (draft) PR that should add support: https://github.com/MobiVM/robovm/pull/605

**Comment by tommyettinger** [comment]
I updated the RoboVM plugin to 2.3.15 in the latest release (1.10.0.11). If you can try it, it would be really helpful, because I don't have a Mac or iOS device. I did make a project with RoboVM 2.3.15 on Windows and it at least doesn't interfere with other modules.

**Comment by tommyettinger** [comment]
RoboVM has updated at least once since the last comment here, and I think it's working now based on other reports. I think I can close this.
