### ISSUE TITLE
RegExodus version in conjunction with TypingLabel

### ISSUE THREAD

**Issue by raeleus** [tommyettinger/gdx-liftoff#9]
Checkmarking TypingLabel in the Third Party Extensions tab results in the following generated code:
```java
api "com.github.tommyettinger:regexodus:$typingLabelVersion"
```
This isn't correct because the latest version of RegExodus is 0.1.10 and does not correlate to the version of TypingLabel. Maybe RegExodus could be a separate check mark in the list and it could be automatically checked when folks select typing label. Sorry for the trouble.

**Comment by tommyettinger** [comment]
I changed something here... I'm not sure when, but I think I just fixed it in the latest commit. Your TenPatches are coming up next, as per #7 , then I will generate a project with all the libraries and see what breaks.

**Comment by tommyettinger** [comment]
Yep, it seems fixed now. I'll push a release; I added Spine, TenPatch and some of my libraries, plus some things from earlier, like ShapeDrawer. From `html/build.gradle` :

```groovy
	api "com.rafaskoberg.gdx:typing-label:$typingLabelVersion:sources"
	api "com.github.tommyettinger:regexodus:$regExodusVersion:sources"
```

**Comment by tommyettinger** [comment]
This is fixed in https://github.com/tommyettinger/gdx-liftoff/releases/tag/v1.9.10.6 .
