### ISSUE TITLE
Creating a demo app with each release to show the changes

### ISSUE THREAD

**Issue by MRZ07** [tommyettinger/gdx-liftoff#94]
Since I have several projects, it would be a great advantage to see which configurations changed in Gradle, for example. Currently, I have to create a demo project and look via git what changes have happened in the configuration of the project. It would be easier to update a demo project with every release, where you can see the changes of the new release. This way, you can also easily update projects that were created with an older version.

**Comment by tommyettinger** [comment]
That's a good idea for sure. A lot of times the changes are fairly minimal, or confined to just a file or two, so checking the commit history would be easier. I'll try to get going on this sometime soon; it shouldn't be too hard.

**Comment by MRZ07** [comment]
When can this feature be expected?

**Comment by tommyettinger** [comment]
Well, I've thought about this a little, and very frequently the changes in a new version only apply to one or a few platforms, or only change some aspect of an extension/library. All of the demo projects would need to use all platforms and maybe all extensions, so that changes could be seen... I'm not sure what is the best way to do this.

**Comment by MRZ07** [comment]
In my opinion, this should make profound changes such as Gradle script changes visible, the extensions are in most cases only version updates. Therefore, I see the different platforms more in focus. An advantage would be a base configuration which creates a new demo project with every release via command line.

**Comment by czyzby** [comment]
> I'm not sure what is the best way to do this.

Automate. 😎

A new commit with a generated project demo will be pushed on every release to:
- [tommyettinger/gdx-liftoff-demo](https://github.com/tommyettinger/gdx-liftoff-demo): Java w/GWT
- [tommyettinger/gdx-liftoff-demo-kotlin](https://github.com/tommyettinger/gdx-liftoff-demo-kotlin): Kotlin w/TeaVM

**Comment by czyzby** [comment]
Wrapper validation might make more sense in a PR check workflow. The first one does seem reasonable, I'll look into it.

**Comment by czyzby** [comment]
I think this issue can be closed now? The projects are now generated automatically from tags, and you can see the changes from version to version in the commit history.

**Comment by tommyettinger** [comment]
Yep, it seems to work! Thanks for all your work on this.
